### ISSUE TITLE
Kontakt

### ISSUE THREAD

**Issue by dakira** [z0mt3c/z0mt3c.github.io#1]
Moin, da ich keine andere Kontaktmöglichkeit gefunden habe, schreibe ich dir einfach mal eben hier. Habe [diesen](https://forum.vodafone.de/t5/Internet-Geräte/Eintragung-eigener-DNS-Server-in-die-6490-unter-OS-6-50-nicht/td-p/1270234/page/2) thread im Vodafone Kundenforum gefunden und nehme an, dass es sich da um dich handelt.

Da ich gerade eine Lösung gefunden habe, dachte ich, dass ich sie mal weitergebe. ;)

Lad dir einfach den [FBEditor](https://github.com/mypikachu/FBEditor/releases).

- FritzBox-Config exportieren (passwort dazu festlegen)
- FBEditor starten (hier das Passwort angeben)
- Config öffnen, nach servercfg suchen und benötigte Einstellungen anpassen
- speichern und diese Config in der FritzBox importieren.
- profit

**Comment by z0mt3c** [comment]
danke, schau ich mir mal an - hab aber auf eigene hardware umgestellt ;-)
